### PR TITLE
Hexagonal grid with horizontal layout

### PR DESCRIPTION
**Pull request by andrekampert**
Currently hexagonal grids have a vertical layout. This adds an additional hexagonal grid with horizontal layout.

### CODE REVIEW

**Comment by nik0kin** [comment]
bump :+1:

**Comment by andrekampert** [comment]
Comments have been updated long since, can be merged

**Comment by jimbojw** [comment]
Sorry for the delay—figured I'd get an email or something automatically when it was taken care of. Thanks again for your interest in the project!

**Comment by andrekampert** [comment]
Ah, me too. Good to know you don't. Thanks for the merge.

**Pull request merged**
